### ISSUE TITLE
Feature Request: migrate from gym to gymnasium

### ISSUE THREAD

**Issue by elliottower** [inpefess/gym-saturation#98]
Hi, this repository is currently listed in the gymnasium [third party environments](https://gymnasium.farama.org/environments/third_party_environments/) but we are cleaning the list up to only include maintained gymnasium-compatible repositories.  

Would it be possible for it to be upgraded from gym to gymnasium? [Gymnasium](https://github.com/Farama-Foundation/Gymnasium) is the maintained version of openai gym and is compatible with current RL training libraries ([rllib](https://github.com/ray-project/ray/tree/master/rllib) and [tianshou](https://github.com/thu-ml/tianshou) have already migrated, and [stable-baselines3](https://github.com/DLR-RM/stable-baselines3/blob/e5deeed16efb57c34ccdcb14692439154d970527/docs/guide/install.rst#bleeding-edge-version) will soon).  

For information about upgrading and compatibility, see [migration guide](https://gymnasium.farama.org/content/migration-guide/) and [gym compatibility](https://gymnasium.farama.org/content/gym_compatibility/). The main difference is the API has switched to returning `truncated` and `terminated`, rather than `done`, in order to give more information and mitigate edge case issues.

**Comment by inpefess** [comment]
> Would it be possible for it to be upgraded from gym to gymnasium?

Hi! Thank you for the feature request. gym-saturation uses Gymnasium from version v0.8.0 (around three weeks ago), and it's mentioned in the documentation: https://github.com/inpefess/gym-saturation#how-to-use

**Comment by elliottower** [comment]
> > Would it be possible for it to be upgraded from gym to gymnasium?
> 
> Hi! Thank you for the feature request. gym-saturation uses Gymnasium from version v0.8.0 (around three weeks ago), and it's mentioned in the documentation: https://github.com/inpefess/gym-saturation#how-to-use

Thanks for the reply, guess I must have missed that somehow, my fault. Great to hear, I’ll update the third party repos page accordingly. If you have any up to date training tutorials which you’d like to be included as examples feel free to comment here, we’re compiling a list of training examples with third party libraries so new users can have an easier time getting started training.

**Comment by inpefess** [comment]
> Thanks for the reply, guess I must have missed that somehow, my fault.

No problem, you're welcome.

> If you have any up to date training tutorials which you’d like to be included as examples feel free to comment here, we’re compiling a list of training examples with third party libraries so new users can have an easier time getting started training.

Do you have any examples/templates/best practices for the tutorials you're looking for? Should it be something like [this](https://gymnasium.farama.org/tutorials/training_agents/blackjack_tutorial/)? I have recently added a couple of training examples (using Ray RLlib) to the [documentation](https://gym-saturation.readthedocs.io/en/latest/experiments.html), but they are far from being user-friendly. So, I will gladly improve them if you show me the right direction.

**Comment by elliottower** [comment]
There aren’t any concrete plans yet but on pettingzoo (multi agent version of gymnasium) I’m compiling a list of tutorials/example scripts using various libraries, just to save people some effort when getting started. The gymnasium tutorial you linked is definitely a good example but that level of polish isn’t needed for third party tutorials. 

The tidbits about DQN convergence on your tutorial page are super helpful imo for example, embedding the code to that page through an {eval-rst} block or directly linking the files from the tutorial page, and some good commenting in the code are all I think are necessary. 

My current plan is to put a brief bullet with training tutorials underneath third party repos if they do have working tutorials, there’s currently a sentence or two description underneath each one (https://gymnasium.farama.org/environments/third_party_environments/)

**Comment by elliottower** [comment]
Added your env to the c urrent third party repos list.

**Comment by inpefess** [comment]
> Added your repo to the current third party repos list.

Thank you!

Could I propose tutorial links later, e.g. through a doc-only PR to Gymnasium repo?

**Comment by elliottower** [comment]
Not sure exactly where they would want third party tutorials to be, there’s been talks about making a separate page with overview of ML libraries and then use that to have links to all training resources/examples which are useful, or maybe just add a link to a landing page for all your repos training tutorials on the third party repos page.

**Comment by inpefess** [comment]
OK, then I think this feature request is completed. Thank you for reminding me about the tutorials!
